name = "HuggingFaceTransformers"
uuid = "a35c7971-d05f-4fd8-a0e9-a051a316e216"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
