name = "HuggingFaceTransformers"
uuid = "a35c7971-d05f-4fd8-a0e9-a051a316e216"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
